### ISSUE TITLE
Custom protocol for rendering and control flow comparisons

### ISSUE THREAD

**Issue by tmjoen** [markglenn/liquex#11]
I ran into a little snag with the handling of structs through the String.Chars that I mentioned in #9.

I have two structs: a `%Global{}` and a `%Var{}`. Both these have a field called `type` that could be `text`/`color`/`boolean`/`markdown`/etc.

Originally I defimpl'ed them with `String.Chars:to_string`, which works fine for rendering them. The problem appeared when using them in some sort of control flow. I can't compare my `%Global{type: :boolean, data: %{value: "false"}}` with `"false"`.

If there was a protocol for `Liquex` it could work:

```elixir
defprotocol Liquex.Protocol do
  @fallback_to_any true
  @spec render(t) :: any()
  def render(value)
end

defimpl Liquex.Protocol, for: Any do
  def render(value), do: to_string(value)
end
```

This falls back to the `to_string` that you use today.

So if I change the left/right logic in `Liquex.Expression`:

```elixir
# wrapped `left` and `right` in Protocol
alias Liquex.Protocol

defp do_eval({left, op, right}), do:
    apply(Kernel, op, [Protocol.render(left), Protocol.render(right)])
```

and call the protocol for object rendering in `Liquex.Render.Object`:
```elixir
  def do_render([argument, filters: filters], %Context{} = context) do
    {result, context} =
      argument
      |> List.wrap()
      |> Argument.eval(context)
      |> Filter.apply_filters(filters, context)

    # pass result through protocol
    {Protocol.render(result), context}
  end
```

then I can have full control of my custom structs if I implement the `Liquex.Protocol` protocol:

```elixir
  defimpl Liquex.Protocol, for: Brando.Sites.Global do
    # ...
    def render(%{type: "boolean", data: data}) do
      data
      |> Map.get("value", "false")
      |> to_string()
    end
    # ...
  end
```

Is this something you'd consider?

If not, sorry for the noise! It's just that this library has solved 99% of my problems and the only one remaining is this :smile:

**Comment by markglenn** [comment]
I see what you're trying to get at, but I think you're mixing two concepts together.  One is the display of an object in the liquid template.  The other is overriding an expression with one of your structs.

For the first, representers were originally the path towards how to render an object in Liquid, however being able to use atom keys now puts that whole system in question, so I expect that will be rewritten in the next major release and should hopefully handle what you're doing using the `String.Chars` protocol.

Overriding an expression is a bit more difficult.  If I switched it over to using your method, where we only compare string values, that will break things.  For example `nil == ""` would suddenly be true.  I still prefer delegating to elixir's built in comparators.  You _can_ override these, but it's difficult to get that injected without forking the entire codebase.

I guess I'm not following what `%Global{}` and `%Var{}` are supposed to do and why you need to compare them to a basic type.  Maybe there's something we can think of around anonymous functions that are currently allowed in the context.

**Comment by tmjoen** [comment]
Thanks for taking a look! 

I suspect I am overcomplicating things a bit for myself -- I could just as well enum all my `%Global`s and `%Var`s to their actual rendered value (basic type) before sticking them into Liquex's context.

**Comment by markglenn** [comment]
Reaching back out on this.

Were you able to find something that works for you?  One thing that isn't well documented is that there is a private map within the `Liquex.Context` that is not available to the liquid template.  You can store anything in here that you wish and access it from your own renderer or filters.  For example, I use it to host the `Plug.Conn` in my own app.

It doesn't solve your immediate problem with comparison operators, but maybe it is of some use here.

```elixir
  @spec build_context(Plug.Conn.t(), any) :: Liquex.Context.t()
  def build_context(conn, params) do
    %Context{
      private: %{conn: conn},
      render_module: EnologyWeb.Liquid.TagRender,
      filter_module: EnologyWeb.Liquid.Filter
    }
    |> Context.assign(:params, params)
    |> Context.assign(:user, user(conn))
    ...
  end
```

**Comment by tmjoen** [comment]
Nice, thanks, that will probably come in handy!

The solution I mentioned in my previous comment worked fine (pre-parse my variables before adding them to the context). It's not so many vars, so the performance hit is microscopical. I'll close the issue :)
