### ISSUE TITLE
Question about Live View

### ISSUE THREAD

**Issue by joselo** [markglenn/liquex#2]
First of all sorry to ask this here, this library it's just amazing I'm creating a kind of clone of shopify and it would be really nice if I can use this library with LiveView. I'm using LiveView and I'm thinking to create components like header, cart, collections. etc. I wonder if is there any good approach to integrate liveview components with this library of how can I render a liquex template but at the same time have liveview components.

Thanks again for this incredible library

**Comment by markglenn** [comment]
I'm glad you're liking the library.

There's nothing special about the output from Liquex that you couldn't just directly inject it into your leex or ~L templates.  What you will get back is iodata that can be placed directly into the contents.

If you look at the basic example in the docs, you can expand it out to do this:

```elixir
  def render(assigns) do
    ~L"""
      Liquid template: <%= Phoenix.HTML.raw render_template(@template, @variables) %>
    """
  end

  @spec render_template(String.t(), map) :: String.t()
  defp render_template(template, vars) do
    with {:ok, template_ast} <- Liquex.parse(template),
         context <- Liquex.Context.new(vars),
         {content, _context} <- Liquex.render(template_ast, context) do
      content
    else
      _ -> "Error generating template"
    end
  end
```

Note that I call out to a function to generate the liquid template results.  This is needed by LiveView to properly track changes.  See the docs here: https://hexdocs.pm/phoenix_live_view/assigns-eex.html#liveeex-pitfalls.

**Comment by joselo** [comment]
Excellent thanks so much for the example !!
