### ISSUE TITLE
requires elixir version ~> 1.10 

### ISSUE THREAD

**Issue by barrieloydall** [markglenn/liquex#32]
Looks like the [project elixir version](https://github.com/markglenn/liquex/blob/d655c9b16260bb34d540a4079ea796136e33b669/mix.exs#L10) needs to be at least `~> 1.10` due to using `is_struct` in guards. I hit a compile error trying to use in a project with `~> 1.9` 

Thanks for creating this package, look forward to using it and swapping out the old Liquid package that had no whitespace control.

**Comment by markglenn** [comment]
Thanks for letting me know. I have a new major release (0.8.0) that is coming out which ups the elixir minimum version to 1.10.  Are you able to update to 1.10+?

I will also update the 0.7.x branch to fix this elixir version mismatch.

**Comment by barrieloydall** [comment]
Yep, 1.10+ is an easy upgrade for us. It is a small library that uses liquid, all our core services that use that library are ahead of 1.10.

Thanks

**Comment by markglenn** [comment]
This was fixed in the 0.8 release.
