### ISSUE TITLE
Parser "shortcuts" made private

### ISSUE THREAD

**Issue by tmjoen** [markglenn/liquex#36]
Hello!

In 0.8.0 a lot of what I call "parser shortcuts" were made private. For instance `Liquex.Parser.Object.arguments`. I found it helpful to use these in my custom tags, but now that they are private I can't :)

Should I just copy these small functions out to my own code base so you can keep their API private and have more freedom to change them?

Thanks for any advice -- still love the library <3

**Comment by markglenn** [comment]
I've opened up more of the helper methods in 0.9.0. Check that out and let me know if there are still some missing.

**Comment by tmjoen** [comment]
That covered everything I needed at least. Thanks so much!
